version: '3.8'

services:

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test
    depends_on:
      - db
      - redis
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo-net
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: odoo2
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - odoo-net
    restart: unless-stopped

networks:
  odoo-net:
    driver: bridge

volumes:
  pgdata:
  addons:
  logs:
