version: "3.1"

services:
  odoo:
    image: odoo:19.0
    container_name: hso_lubricant
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8079:8069"                      # <- puerto externo distinto al primer stack
    volumes:
      - odoo-data-2:/var/lib/odoo
      - ./config2:/etc/odoo              # opcional: odoo.conf propio
      - ./addons2:/mnt/extra-addons      # módulos propios de esta instancia
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${ODOO_DB_PASSWORD:-odoo}
    # Arranca sin crear base para mostrar el gestor
    command: >
      odoo
      --db_host=db --db_port=5432
      --db_user=odoo --db_password=${ODOO_DB_PASSWORD:-odoo}
      --db-filter=.*
      --logfile=/var/log/odoo/odoo.log

  db:
    image: postgres:16.0
    container_name: db2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres             # evita pre-crear una BD "odoo" vacía
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD:-odoo}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data-2:/var/lib/postgresql/data

volumes:
  odoo-data-2:
  db-data-2:
